import React, { useState, useEffect } from 'react';
import { Sparkles, Video, Play, Loader2, AlertCircle } from 'lucide-react';
import { generateSummaryVideo } from '../services/geminiService';

interface OverviewViewProps {
  overviewText: string;
  videoUrl?: string;
  onVideoGenerated: (url: string) => void;
}

const LOADING_MESSAGES = [
  "Drafting the storyboard...",
  "Rendering high-quality visuals...",
  "Applying cinematic effects...",
  "Finalizing the video output...",
  "Almost there, polishing the details..."
];

const OverviewView: React.FC<OverviewViewProps> = ({ overviewText, videoUrl, onVideoGenerated }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);

  useEffect(() => {
    let interval: number;
    if (loading) {
      interval = window.setInterval(() => {
        setLoadingMessageIndex((prev) => (prev + 1) % LOADING_MESSAGES.length);
      }, 4000);
    } else {
      setLoadingMessageIndex(0);
    }
    return () => clearInterval(interval);
  }, [loading]);

  const handleGenerateVideo = async () => {
    setLoading(true);
    setError(null);
    try {
      const url = await generateSummaryVideo(overviewText);
      onVideoGenerated(url);
    } catch (err: any) {
      console.error("Video generation error:", err);
      
      const errorMessage = err.message || JSON.stringify(err);
      
      // Handle the specific 404/Not Found error which usually means missing permissions/project selection
      if (
        errorMessage.includes("404") || 
        errorMessage.includes("Requested entity was not found") || 
        errorMessage.includes("NOT_FOUND")
      ) {
        try {
          // Trigger the key selection dialog again
          await window.aistudio.openSelectKey();
          
          // Retry generation immediately after key selection
          setLoadingMessageIndex(0); // Reset loading message
          const url = await generateSummaryVideo(overviewText);
          onVideoGenerated(url);
          return;
        } catch (retryErr) {
          setError("Failed to generate video. Please ensure you selected a paid Google Cloud Project.");
        }
      } else {
        setError("Failed to generate video. Please try again later.");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Text Overview Card */}
      <div className="bg-gradient-to-br from-indigo-50 to-white p-8 rounded-xl border border-indigo-100 shadow-sm">
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-indigo-100 p-2 rounded-lg">
            <Sparkles className="w-6 h-6 text-indigo-600" />
          </div>
          <h2 className="text-2xl font-bold text-indigo-900">
            Video Overview
          </h2>
        </div>
        <p className="text-slate-700 leading-relaxed text-lg">
          {overviewText}
        </p>
      </div>

      {/* Video Generation Section */}
      <div className="bg-slate-900 text-white p-8 rounded-xl shadow-lg overflow-hidden relative min-h-[400px] flex flex-col items-center justify-center border border-slate-700">
        {videoUrl ? (
          <div className="w-full h-full flex flex-col items-center animate-fade-in">
             <div className="w-full flex items-center gap-2 mb-4 text-emerald-400">
                <Video className="w-5 h-5" />
                <span className="font-semibold">AI Generated Preview</span>
             </div>
            <video 
              controls 
              autoPlay 
              className="w-full rounded-lg shadow-2xl border border-slate-700 bg-black aspect-video"
              src={videoUrl}
            />
            <p className="mt-4 text-slate-400 text-sm">Generated by Veo</p>
          </div>
        ) : (
          <div className="text-center max-w-md z-10">
            <div className="mb-6 flex justify-center">
              <div className="bg-indigo-500/20 p-4 rounded-full ring-1 ring-indigo-500/50">
                 <Video className="w-12 h-12 text-indigo-400" />
              </div>
            </div>
            
            <h3 className="text-2xl font-bold mb-3">Visualize this Content</h3>
            <p className="text-slate-300 mb-8 text-lg">
              Generate a short cinematic AI video summarizing these concepts using Google's Veo model.
            </p>
            
            {error && (
               <div className="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-lg flex items-center gap-3 text-red-200 text-left">
                  <AlertCircle className="w-5 h-5 flex-shrink-0" />
                  <p className="text-sm">{error}</p>
               </div>
            )}

            <button
              onClick={handleGenerateVideo}
              disabled={loading}
              className="group relative inline-flex items-center gap-3 px-8 py-4 bg-indigo-600 hover:bg-indigo-500 rounded-xl font-bold text-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-indigo-500/25"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating Video...
                </>
              ) : (
                <>
                  <Play className="w-5 h-5 fill-current" />
                  Generate AI Video
                </>
              )}
            </button>
            
            {loading && (
               <div className="mt-6 text-sm text-slate-400 animate-pulse flex flex-col items-center gap-2">
                 <p className="text-indigo-300 font-medium text-base">
                   {LOADING_MESSAGES[loadingMessageIndex]}
                 </p>
                 <p>This may take 1-2 minutes.</p>
               </div>
            )}
          </div>
        )}
        
        {/* Decorative background elements */}
        {!videoUrl && (
          <>
            <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-indigo-900/40 via-slate-900 to-slate-900 -z-0 pointer-events-none"></div>
            <div className="absolute bottom-0 right-0 w-64 h-64 bg-indigo-600/10 blur-[100px] rounded-full pointer-events-none"></div>
          </>
        )}
      </div>
    </div>
  );
};

export default OverviewView;